[package]
name = "wasmi-coremark"
version = "0.1.0"
authors = ["clearloop <udtrokia@gmail.com>"]
edition = "2018"

[[bin]]
name = "bm"
path = "main.rs"

[dependencies]
wasmtime = "0.40.0"
wasm3 = { version = "0.3.1", features = ["build-bindgen"] }
wasmi = "0.16.0"
