[package]
name = "wasmi-coremark"
version = "0.1.0"
authors = ["clearloop <udtrokia@gmail.com>"]
edition = "2018"

[[bin]]
name = "bm"
path = "main.rs"

[dependencies]
async-std = { version = "1.9.0", features = ["attributes"]}
futures = "0.3.13"
wasmi = "0.8.0"
wasmtime = "0.25.0"
wasm3 = { version = "0.1.3", features=["build-bindgen"]}
